config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :test_helpers do
    post "sign_in", to: "sessions#create"
  end

  namespace :admin do
    resources :case_details do
      resources :rights_violations, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :collective_victims
      resources :individual_victims
      resources :criminalizations
      resources :killings
    end
    resources :rights_violations, shallow: true do
      resources :perpetratorizations
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue
    ActiveAdmin::DatabaseHitDuringLoad
  end

  root "documenters/sessions#new"

  resources :development_projects, only: [:show, :edit, :update]
  resources :case_details, except: [:destroy] do
    resources :victims, only: [:index], controller: "case_details/victims"
    resources :individual_victims, only: [:new, :create], controller: "case_details/individual_victims"
    resources :collective_victims, only: [:new, :create], controller: "case_details/collective_victims"
    resources :criminalizations, only: [:index, :new, :create, :edit, :update], controller: "case_details/criminalizations"
    resources :human_rights_violations, only: [:index, :new, :create, :edit, :update], controller: "case_details/human_rights_violations"
    resources :killings, only: [:index, :new, :create, :edit, :update], controller: "case_details/killings"
    resources :development_projects, only: [:index, :new, :create], controller: "case_details/development_projects"
    resources :tags, only: [:index, :create], controller: "case_details/tags"
  end

  namespace :ip_rights do
    resources :case_details, only: [:show] do
      resources :data_sharings,           only: [:new, :create]
      resources :incident_details,        only: [:new, :create]
      resources :victims,                 only: [:index]
      resources :individual_victims,      only: [:new, :create]
      resources :collective_victims,      only: [:new, :create]
      resources :human_rights_violations, only: [:index, :new, :create]
      resources :criminalizations,        only: [:new, :create]
      resources :killings,                only: [:new, :create]
      resources :impact_and_actions,      only: [:new, :create]
      resources :development_projects,    only: [:index, :new, :create]
      resources :submissions, only: [:create]
    end

    resources :documenter_details, only: [:new, :create]
  end

  resources :case_imports, only: [:show]

  resources :draft_case_details, only: [:show, :update] do
    resource :publication, only: [:create], controller: "draft_case_details/publications"
  end

  namespace :documenters do
    resources :case_imports, only: [:new, :create]
    resources :documenter, only: [] do
      resource :locale
    end
    get "/login", to: "sessions#new"
    post "/sessions", to: "sessions#create"
    delete "/sessions", to: "sessions#destroy"
    resources :dashboard, only: [:index]
    resources :individual_victims, only: [:index, :show] do
      resources :case_details, only: [:index], controller: "/documenters/individual_victims/case_details"
    end
    resources :collective_victims, only: [:index, :show, :edit, :update]
    resources :case_details, only: [:index, :new, :show] do
      resources :individual_victims, only: [:new, :create, :show, :edit, :update, :index], controller: "case_details/individual_victims"
      resources :collective_victims, only: [:new, :create, :edit, :update, :show, :index], controller: "case_details/collective_victims"
      resources :criminalizations, only: [:index, :new, :create, :edit, :update, :show], controller: "case_details/criminalizations"
      resources :human_rights_violations, only: [:index, :new, :create, :edit, :update], controller: "case_details/human_rights_violations"
      resources :killings, only: [:index, :new, :create, :edit, :update], controller: "case_details/killings"
      resources :development_projects, only: [:index, :new, :create, :show, :edit, :update], controller: "case_details/development_projects"
      resources :tags, only: [:create, :destroy], controller: "case_details/tags"
    end
  end

  resources :countries, only: [:index, :show] do
    resources :killings, only: [:index], controller: "countries/killings"
    resources :criminalizations, only: [:index], controller: "countries/criminalizations"
    resources :human_rights_violations, only: [:index], controller: "countries/human_rights_violations"
  end

  resources :killings, only: [:index, :show, :edit, :update]
  resources :criminalizations, only: [:index]
  resources :human_rights_violations, only: [:index]

  resources :case_details, only: [:edit, :update] do
    resources :development_projects, only: [:new, :create], controller: "case_details/development_projects"
  end
end

app/models/case_details/actions_undertaken.rb
# frozen_string_literal: true

module CaseDetails
  class ActionsUndertaken < ApplicationRecord
    belongs_to :case_detail
  end
end

app/models/case_details/draft_case_detail.rb
# frozen_string_literal: true

class CaseDetails::DraftCaseDetail < ApplicationRecord
  belongs_to :case_import
  belongs_to :country, optional: true
  belongs_to :age_bracket, class_name: "AgeBracket", optional: true
end

app/controllers/case_details_controller.rb
# frozen_string_literal: true

class CaseDetailsController < Documenters::BaseController
  layout "documenter"
  def index
    outcome = ::CaseDetails::Index.run(params.merge!(documenter: current_documenter))
    @country = Country.find_by(id: params[:country_id])
    @pagy, @case_details = pagy(outcome.result)

    respond_to do |format|
      format.html
      format.turbo_stream 
    end
  end

  def show
    @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:id))
    respond_to do |format|
      format.html
      format.turbo_stream do 
        render partial: "documenters/case_details/partials/show", 
        locals: { case_detail: @case_detail } 
      end
      format.pdf do
        pdf = CaseDetailPdf.new(@case_detail, view_context)
        send_data pdf.render, filename: "case_detail_#{@case_detail.id}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end
  
  def edit
    @case_detail = CaseDetails::CaseDetail.find(params[:id])
  end

  def update
    @case_detail = CaseDetails::CaseDetail.find(params[:id])
    @case_detail.update(case_detail_params)
    if @case_detail.valid?
      @case_detail.save
      respond_to do |format|
        format.html { redirect_to documenters_case_detail_url(@case_detail) }
      end
    else
      respond_to do |_format|
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private

  def case_detail_params
    params.require(:case_details_case_detail)
      .permit(
        :documenter_first_name,
        :documenter_last_name,
        :organization_name,
        :submission_date_year,
        :submission_date_month,
        :submission_date_day,
        :documenter_email,
        :documenter_phone_number,
        :data_sources,
        :data_sharing,
        :primary_data,
        :country_id,
        :subnational_location,
        :location_details_1,
        :location_details_2,
        :incident_start_month,
        :incident_start_day,
        :incident_start_year,
        :incident_end_month,
        :incident_end_day,
        :incident_end_year,
        :incident_hour,
        :incident_minute,
        :actions_taken_details,
        :incident_investigation_details
      )
  end
end

app/controllers/documenters/case_details/collective_victims_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class CollectiveVictimsController < Documenters::BaseController
      layout "documenter"

      before_action :set_case_detail
      before_action :set_collective_victim, only: [:show, :edit, :update]

      def index
        @collective_victims = @case_detail.collective_victims
      end

      def show; end

      def new
        @collective_victim = ::CaseDetails::Victims::Collective.new
      end

      def edit
        build_missing_age_bracket_breakdowns
      end

      def create
        @collective_victim = ::CaseDetails::Victims::Collective.new(collective_victim_params)

        if @collective_victim.valid?
          @collective_victim.process!
          redirect_to(documenters_case_detail_collective_victims_url(@case_detail))
        else
          render(:new, status: :unprocessable_entity)
        end
      end

      def update
        if @collective_victim.update(update_params)
          redirect_to(documenters_case_detail_collective_victim_url(@case_detail, @collective_victim))
        else
          build_missing_age_bracket_breakdowns if @collective_victim.age_bracket_breakdowns.empty?
          render(:edit, status: :unprocessable_entity)
        end
      end

      private

      def set_case_detail
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
      end

      def set_collective_victim
        @collective_victim = Victims::CollectiveVictim.find(params[:id])
      end

      def collective_victim_params
        base_params(:case_details_victims_collective)
          .merge(case_detail_id: @case_detail.id)
      end

      def update_params
        base_params(:victims_collective_victim)
      end

      def base_params(key)
        params.require(key).permit(
          :affected_total,
          :collective_victim_category_id,
          :indigenous_group_description,
          :refer_to_individuals,
          :victim_details,
          :male_total,
          :female_total,
          age_bracket_breakdowns_attributes: [:id, :age_bracket_id, :total, :_destroy],
        )
      end

      def build_missing_age_bracket_breakdowns
        existing_ids = @collective_victim.age_bracket_breakdowns.map(&:age_bracket_id)
        AgeBracket.where.not(id: existing_ids).each do |ab|
          @collective_victim.age_bracket_breakdowns.build(age_bracket_id: ab.id)
        end
      end
    end
  end
end

app/controllers/documenters/case_details/criminalizations_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class CriminalizationsController < Documenters::BaseController
      layout "documenter"
      
      before_action :set_case_detail

      def index
        @criminalizations = @case_detail.criminalizations
      end

      def new
        @criminalization = @case_detail.criminalizations.build
        @criminalization.accuserizations.build
       
      end

      def create
        @criminalization = @case_detail.criminalizations.create!(criminalization_params)
        if @criminalization.valid?
          @criminalization.save

          respond_to do |format|
            format.html do
              redirect_to documenters_case_detail_criminalization_url(case_detail_id: @case_detail.id, id: @criminalization.id)
            end
          end
        else
          respond_to do |format|
            format.html do
              render :new, status: :unprocessable_entity
            end
          end
        end
      end

      def show
        @criminalization = @case_detail.criminalizations.find(params[:id])
      end

      def edit
        @criminalization = @case_detail.criminalizations.find(params[:id])
        Criminalizations::AccuserCategory.all.each do |category|
    unless @criminalization.accuserizations.exists?(accuser_category_id: category.id)
      @criminalization.accuserizations.build(accuser_category_id: category.id)
    end
  end
      end

      def update
        @criminalization = @case_detail.criminalizations.find(params[:id])
        
        if @criminalization.update!(criminalization_params)
          
              redirect_to documenters_case_detail_criminalization_url(case_detail_id: @case_detail.id, id: @criminalization.id)
            
        else
         
              render :edit, status: :unprocessable_entity
           

        end
      end

      private
      def set_case_detail
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
      end

      def criminalization_params
        params.require(:criminalizations_criminalization)
          .permit(
            :criminalization_details,
            :experienced_harrassment_or_intimidation,
            :harrassment_or_intimidation_details,
            :accusation_or_charges_details,
            :policies_or_laws_used,
            :accuser_details,
            :case_filing_status,
            :case_filing_details,
            :case_decision_status,
            :case_decision_details,
            :victims_in_detention,
            :victims_in_detention_details,
            :case_filing_against_perpetrator,
            :case_filing_against_perpetrator_details,
            :state_action_to_address_criminalization,
            :state_action_to_address_criminalization_details,
            :investigation_on_criminalization,
            :investigation_on_criminalization_details,
            :impact_to_victim_details,
            :impact_to_community_details,
            accuser_category_ids: []
          )
      end
    end
  end
end

app/controllers/documenters/case_details/development_projects_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class DevelopmentProjectsController < Documenters::BaseController
      layout "documenter"

      def index
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
        @development_projects = @case_detail.development_projects
      end

      def show
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = @case_detail.development_projects.find(params[:id])
      end

      def new
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = ::CaseDetails::DevelopmentProject.new
      end

      def edit
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = DevelopmentProjects::DevelopmentProject.find(params[:id])
      end

      def create
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = ::CaseDetails::DevelopmentProject.new(development_project_params)
        if @development_project.valid?
          @development_project.save!
          redirect_to(documenters_case_detail_development_projects_url(@case_detail))
        else
          render(:new, status: :unprocessable_entity)
        end
      end

      def update
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = @case_detail.development_projects.find(params[:id])
        @development_project.update(edit_development_project_params)
        if @development_project.valid?
          @development_project.save
          redirect_to(documenters_case_detail_development_project_url(id: @development_project.id, case_detail_id: @case_detail.id))
        else
          render(:edit, status: :unprocessable_entity)
        end
      end

      private

      def edit_development_project_params
        params.require(:development_projects_development_project).permit(
          :development_project_category_id,
          :name,
          :description,
          :project_start_year,
          :website_sources,
          :parent_company_name,
          :parent_company_description,
          :parent_company_data_sources,
          :parent_company_country_id,
          :funding_source_description,
          :funding_source_data_sources,
        )
      end

      def development_project_params
        params
          .require(:case_details_development_project)
          .permit(:project_name,
            :development_project_category_id,
            :project_description,
            :start_of_operation_year,
            :project_documents,
            :project_data_sources,
            :company_profile_known,
            :company_info_status,
            :parent_company_country_id,
            :parent_company_description,
            :parent_company_documents,
            :parent_company_data_sources,
            :funding_profile_known,
            :funding_description,
            :funding_source_ids,
            :funding_source_description,
            :funding_source_documents,
            :funding_source_data_sources,
            :parent_company_name,
            documents: [])
          .merge!(case_detail_id: @case_detail.id)
      end
    end
  end
end

app/controllers/documenters/case_details/tags_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class TagsController < Documenters::BaseController
      layout "documenter"

      before_action :set_case_detail

      def create
        tag = params[:tag]
        @case_detail.tag_list.add(tag)
        @case_detail.save

        respond_to do |format|
          format.turbo_stream
        end
      end

      def destroy
        @case_detail.tag_list.remove(params[:id])
        @case_detail.save!

        respond_to do |format|
          format.turbo_stream
          format.html { redirect_to(@case_detail) }
        end
      end

      private

      def set_case_detail
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
      end
    end
  end
end

app/views/documenters/case_details/individual_victims/_form.html.erb
<div id='case-detail-new-individual-victim-form'>
  <div class="max-w-7xl mx-auto px-10 mt-5 mb-5 py-10 bg-white shadow border-t-4 border-stone-200 space-y-10">
    <%= simple_form_for @individual_victim, url: form_url do |f| %>
      <div class="max-w-7xl mx-auto lg:px-0">
        <h2 class="font-bold text-xl text-gray-900">Individual Victim Details</h2>
        <div class="md:mt-0 md:col-span-2">
          <div class="px-4 py-5 space-y-4 sm:p-6">
            <%= f.input :full_name, label: "Full Name" %>

            <%= f.input :gender, collection: Victims::IndividualVictim.genders.map { |k, v| [v.upcase, k] } %>

            <%= f.input :dependent_type, collection: Victims::IndividualVictim.dependent_types.map { |k, _| [k.titleize, k] } %>

            <label class="block text-sm font-bold text-gray-700">Date of Birth</label>
            <div data-controller="individual-victim">
              <label class="block text-sm font-bold text-gray-900">
                Is the victim's date of birth known?
              </label>
              <%= f.input :date_of_birth_known, label: '', collection: ['No', 'Yes'], checked: 'No',
                  input_html: { data: { individual_victim_target: "input", action: "click->individual-victim#toggle" } },
                  as: :radio_buttons %>

              <div data-individual-victim-target="output">
                <div class="grid grid-cols-3 gap-4">
                  <%= f.input :date_of_birth_month, label: false, include_blank: 'Please Select', collection: Date::MONTHNAMES %>
                  <%= f.input :date_of_birth_day, label: false, include_blank: 'Please Select', collection: 1..31 %>
                  <%= f.input :date_of_birth_year, label: false, include_blank: 'Please Select', collection: (Date.current.year - 100)..Date.current.year %>
                </div>
              </div>
            </div>

            <%= f.input :age_bracket_id, label: "Age Bracket", collection: AgeBracket.all.map { |a| [a.description, a.id] } %>

            <%= f.input :dependent_details, as: :text, label: "Dependent Details",
                hint: "E.g., children, partner, grandchildren etc. (List details of dependents.)" %>

            <%= f.input :ethnic_identity, as: :text, label: "Ethnic Identity",
                hint: "Name of Indigenous Peoples’ group or Ethnic Identity of victim" %>

            <%= f.input :victim_role, as: :text, label: "Role of Victim in the Community",
                hint: "E.g., elder, healer, organizer, protester, etc. This captures community involvement." %>

            <div class="border-t border-gray-200 pt-6">
              <%= f.submit "Save Individual Victim", class: "w-full sm:w-auto h-12 px-6 text-white transition-colors duration-150 bg-green-700 rounded-lg focus:shadow-outline hover:bg-green-800" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/documenters/case_details/individual_victims/edit.html.erb
<%= render partial: "form", locals: { form_url: documenters_case_detail_individual_victim_path(@case_detail, @individual_victim) } %>

app/views/documenters/case_details/individual_victims/index.html.erb
<%= render 'documenters/case_details/partials/show', case_detail: @case_detail %>

app/views/documenters/case_details/individual_victims/new.html.erb
<%= render partial: "form", locals: { form_url: documenters_case_detail_individual_victims_path(@case_detail) } %>

app/views/documenters/case_details/individual_victims/show.html.erb
<div class="max-w-7xl mx-auto px-10 mt-5 mb-5 py-10 bg-white shadow border-t-4 border-stone-200 space-y-10">
    <div class="flex flex-col md:flex-row md:items-center md:justify-between space-y-4 md:space-y-0">
      <div>
        <h1 class="text-xl font-bold text-gray-900"><%= @individual_victim.full_name.titleize %></h1>
      </div>
       <div class="flex space-x-3 justify-start md:justify-end">
     <%= link_to "Back", documenters_case_detail_individual_victims_path(@case_detail),
                class: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg" %>
    <%= link_to "Edit", edit_documenters_case_detail_individual_victim_path(id: @individual_victim.id, case_detail_id: @case_detail.id),
                class: "inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-stone-600 hover:bg-stone-700 rounded-lg" %>
   
  </div>
</div>

<div class="border-t border-gray-200 pt-2">
  <h2 class="text-lg font-semibold text-gray-800 mb-2">Gender</h2>
  <p class="text-gray-700">
    <%= @individual_victim.gender.presence || "-" %>
  </p>
</div>

<div class="border-t border-gray-200 pt-2">
  <h2 class="text-lg font-semibold text-gray-800 mb-2">Dependent Type</h2>
  <p class="text-gray-700 whitespace-pre-line">
    <%= @individual_victim.dependent_type.presence || "-" %>
  </p>
</div>

<div class="border-t border-gray-200 pt-6">
  <h2 class="text-lg font-semibold text-gray-800 mb-2">Name of Indigenous Peoples’ group or Ethnic Identity of victim</h2>
  <p class="text-gray-700 whitespace-pre-line">
    <%= @individual_victim.ethnic_identity.presence || "-" %>
  </p>
</div>

<div class="border-t border-gray-200 pt-6">
  <h2 class="text-lg font-semibold text-gray-800 mb-2">Date of Birth</h2>
  <p class="text-gray-700 whitespace-pre-line">
    <%= @individual_victim.date_of_birth.presence || "-" %>
  </p>
</div>

<div class="border-t border-gray-200 pt-6">
  <h2 class="text-lg font-semibold text-gray-800 mb-2">Age Bracket</h2>
  <p class="text-gray-700 whitespace-pre-line">
    <%= @individual_victim.age_bracket&.description || "-" %>
  </p>
</div>

<div class="border-t border-gray-200 pt-6">
  <h2 class="text-lg font-semibold text-gray-800 mb-2">Role of Victim in the Community</h2>
  <p class="text-gray-700 whitespace-pre-line">
    <%= @individual_victim.victim_role || "-" %>
  </p>
</div>

<div class="border-t border-gray-200 pt-6">
  <h2 class="text-lg font-semibold text-gray-800 mb-2">Dependent Details </h2>
  <p class="text-gray-700 whitespace-pre-line">
    <%= @individual_victim.dependent_details || "-" %>
  </p>
</div>