config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :test_helpers do
    post "sign_in", to: "sessions#create"
  end

  namespace :admin do
    resources :case_details do
      resources :rights_violations, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :collective_victims
      resources :individual_victims
      resources :criminalizations
      resources :killings
    end
    resources :rights_violations, shallow: true do
      resources :perpetratorizations
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue
    ActiveAdmin::DatabaseHitDuringLoad
  end

  root "documenters/sessions#new"

  resources :development_projects, only: [:show, :edit, :update]
  resources :case_details, except: [:destroy] do
    resources :victims, only: [:index], controller: "case_details/victims"
    resources :individual_victims, only: [:new, :create], controller: "case_details/individual_victims"
    resources :collective_victims, only: [:new, :create], controller: "case_details/collective_victims"
    resources :criminalizations, only: [:index, :new, :create, :edit, :update], controller: "case_details/criminalizations"
    resources :human_rights_violations, only: [:index, :new, :create, :edit, :update], controller: "case_details/human_rights_violations"
    resources :killings, only: [:index, :new, :create, :edit, :update], controller: "case_details/killings"
    resources :development_projects, only: [:index, :new, :create], controller: "case_details/development_projects"
    resources :tags, only: [:index, :create], controller: "case_details/tags"
  end

  namespace :ip_rights do
    resources :case_details, only: [:show] do
      resources :data_sharings,           only: [:new, :create]
      resources :incident_details,        only: [:new, :create]
      resources :victims,                 only: [:index]
      resources :individual_victims,      only: [:new, :create]
      resources :collective_victims,      only: [:new, :create]
      resources :human_rights_violations, only: [:index, :new, :create]
      resources :criminalizations,        only: [:new, :create]
      resources :killings,                only: [:new, :create]
      resources :impact_and_actions,      only: [:new, :create]
      resources :development_projects,    only: [:index, :new, :create]
      resources :submissions, only: [:create]
    end

    resources :documenter_details, only: [:new, :create]
  end

  resources :case_imports, only: [:show]

  resources :draft_case_details, only: [:show, :update] do
    resource :publication, only: [:create], controller: "draft_case_details/publications"
  end

  namespace :documenters do
    resources :case_imports, only: [:new, :create]
    resources :documenter, only: [] do
      resource :locale
    end
    get "/login", to: "sessions#new"
    post "/sessions", to: "sessions#create"
    delete "/sessions", to: "sessions#destroy"
    resources :dashboard, only: [:index]
    resources :individual_victims, only: [:index, :show] do
      resources :case_details, only: [:index], controller: "/documenters/individual_victims/case_details"
    end
    resources :collective_victims, only: [:index, :show, :edit, :update]
    resources :case_details, only: [:index, :new, :show] do
      resources :individual_victims, only: [:new, :create, :show, :edit, :update, :index], controller: "case_details/individual_victims"
      resources :collective_victims, only: [:new, :create, :edit, :update, :show, :index], controller: "case_details/collective_victims"
      resources :criminalizations, only: [:index, :new, :create, :edit, :update, :show], controller: "case_details/criminalizations"
      resources :human_rights_violations, only: [:index, :new, :create, :edit, :update], controller: "case_details/human_rights_violations"
      resources :killings, only: [:index, :new, :create, :edit, :update], controller: "case_details/killings"
      resources :development_projects, only: [:index, :new, :create, :show, :edit, :update], controller: "case_details/development_projects"
      resources :tags, only: [:create, :destroy], controller: "case_details/tags"
    end
  end

  resources :countries, only: [:index, :show] do
    resources :killings, only: [:index], controller: "countries/killings"
    resources :criminalizations, only: [:index], controller: "countries/criminalizations"
    resources :human_rights_violations, only: [:index], controller: "countries/human_rights_violations"
  end

  resources :killings, only: [:index, :show, :edit, :update]
  resources :criminalizations, only: [:index]
  resources :human_rights_violations, only: [:index]

  resources :case_details, only: [:edit, :update] do
    resources :development_projects, only: [:new, :create], controller: "case_details/development_projects"
  end
end

app/controllers/documenters/base_controller.rb
# frozen_string_literal: true

module Documenters
  class BaseController < ApplicationController
    before_action :authenticate_documenter!
    helper_method :current_documenter
    layout "documenter"
    around_action :switch_locale

    def switch_locale(&action)
      locale = current_documenter ? current_documenter.locale : I18n.default_locale
      I18n.with_locale(locale, &action)
    end

    def current_documenter
      if session[:user_id]
        @documenter = Users::Documenter.find(session[:user_id])
      end
    end

    def logged_in?
      !!current_documenter
    end

    def authenticate_documenter!
      redirect_to documenters_login_path unless logged_in?
    end
  end
end

app/controllers/documenters/case_details/collective_victims_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class CollectiveVictimsController < Documenters::BaseController
      layout "documenter"

      before_action :set_case_detail
      before_action :set_collective_victim, only: [:show, :edit, :update]

      def index
        @collective_victims = @case_detail.collective_victims
      end

      def show; end

      def new
        @collective_victim = ::CaseDetails::Victims::Collective.new
      end

      def edit
        build_missing_age_bracket_breakdowns
      end

      def create
        @collective_victim = ::CaseDetails::Victims::Collective.new(collective_victim_params)

        if @collective_victim.valid?
          @collective_victim.process!
          redirect_to(documenters_case_detail_collective_victims_url(@case_detail))
        else
          render(:new, status: :unprocessable_entity)
        end
      end

      def update
        if @collective_victim.update(update_params)
          redirect_to(documenters_case_detail_collective_victim_url(@case_detail, @collective_victim))
        else
          build_missing_age_bracket_breakdowns if @collective_victim.age_bracket_breakdowns.empty?
          render(:edit, status: :unprocessable_entity)
        end
      end

      private

      def set_case_detail
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
      end

      def set_collective_victim
        @collective_victim = Victims::CollectiveVictim.find(params[:id])
      end

      def collective_victim_params
        base_params(:case_details_victims_collective)
          .merge(case_detail_id: @case_detail.id)
      end

      def update_params
        base_params(:victims_collective_victim)
      end

      def base_params(key)
        params.require(key).permit(
          :affected_total,
          :collective_victim_category_id,
          :indigenous_group_description,
          :refer_to_individuals,
          :victim_details,
          :male_total,
          :female_total,
          age_bracket_breakdowns_attributes: [:id, :age_bracket_id, :total, :_destroy],
        )
      end

      def build_missing_age_bracket_breakdowns
        existing_ids = @collective_victim.age_bracket_breakdowns.map(&:age_bracket_id)
        AgeBracket.where.not(id: existing_ids).each do |ab|
          @collective_victim.age_bracket_breakdowns.build(age_bracket_id: ab.id)
        end
      end
    end
  end
end

app/controllers/documenters/case_details/criminalizations_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class CriminalizationsController < Documenters::BaseController
      layout "documenter"
      
      before_action :set_case_detail

      def index
        @criminalizations = @case_detail.criminalizations
      end

      def new
        @criminalization = @case_detail.criminalizations.build
        @criminalization.accuserizations.build
       
      end

      def create
        @criminalization = @case_detail.criminalizations.create!(criminalization_params)
        if @criminalization.valid?
          @criminalization.save

          respond_to do |format|
            format.html do
              redirect_to documenters_case_detail_criminalization_url(case_detail_id: @case_detail.id, id: @criminalization.id)
            end
          end
        else
          respond_to do |format|
            format.html do
              render :new, status: :unprocessable_entity
            end
          end
        end
      end

      def show
        @criminalization = @case_detail.criminalizations.find(params[:id])
      end

      def edit
        @criminalization = @case_detail.criminalizations.find(params[:id])
        Criminalizations::AccuserCategory.all.each do |category|
    unless @criminalization.accuserizations.exists?(accuser_category_id: category.id)
      @criminalization.accuserizations.build(accuser_category_id: category.id)
    end
  end
      end

      def update
        @criminalization = @case_detail.criminalizations.find(params[:id])
        
        if @criminalization.update!(criminalization_params)
          
              redirect_to documenters_case_detail_criminalization_url(case_detail_id: @case_detail.id, id: @criminalization.id)
            
        else
         
              render :edit, status: :unprocessable_entity
           

        end
      end

      private
      def set_case_detail
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
      end

      def criminalization_params
        params.require(:criminalizations_criminalization)
          .permit(
            :criminalization_details,
            :experienced_harrassment_or_intimidation,
            :harrassment_or_intimidation_details,
            :accusation_or_charges_details,
            :policies_or_laws_used,
            :accuser_details,
            :case_filing_status,
            :case_filing_details,
            :case_decision_status,
            :case_decision_details,
            :victims_in_detention,
            :victims_in_detention_details,
            :case_filing_against_perpetrator,
            :case_filing_against_perpetrator_details,
            :state_action_to_address_criminalization,
            :state_action_to_address_criminalization_details,
            :investigation_on_criminalization,
            :investigation_on_criminalization_details,
            :impact_to_victim_details,
            :impact_to_community_details,
            accuser_category_ids: []
          )
      end
    end
  end
end

app/controllers/documenters/case_details/development_projects_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class DevelopmentProjectsController < Documenters::BaseController
      layout "documenter"

      def index
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
        @development_projects = @case_detail.development_projects
      end

      def show
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = @case_detail.development_projects.find(params[:id])
      end

      def new
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = ::CaseDetails::DevelopmentProject.new
      end

      def edit
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = DevelopmentProjects::DevelopmentProject.find(params[:id])
      end

      def create
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = ::CaseDetails::DevelopmentProject.new(development_project_params)
        if @development_project.valid?
          @development_project.save!
          redirect_to(documenters_case_detail_development_projects_url(@case_detail))
        else
          render(:new, status: :unprocessable_entity)
        end
      end

      def update
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = @case_detail.development_projects.find(params[:id])
        @development_project.update(edit_development_project_params)
        if @development_project.valid?
          @development_project.save
          redirect_to(documenters_case_detail_development_project_url(id: @development_project.id, case_detail_id: @case_detail.id))
        else
          render(:edit, status: :unprocessable_entity)
        end
      end

      private

      def edit_development_project_params
        params.require(:development_projects_development_project).permit(
          :development_project_category_id,
          :name,
          :description,
          :project_start_year,
          :website_sources,
          :parent_company_name,
          :parent_company_description,
          :parent_company_data_sources,
          :parent_company_country_id,
          :funding_source_description,
          :funding_source_data_sources,
        )
      end

      def development_project_params
        params
          .require(:case_details_development_project)
          .permit(:project_name,
            :development_project_category_id,
            :project_description,
            :start_of_operation_year,
            :project_documents,
            :project_data_sources,
            :company_profile_known,
            :company_info_status,
            :parent_company_country_id,
            :parent_company_description,
            :parent_company_documents,
            :parent_company_data_sources,
            :funding_profile_known,
            :funding_description,
            :funding_source_ids,
            :funding_source_description,
            :funding_source_documents,
            :funding_source_data_sources,
            :parent_company_name,
            documents: [])
          .merge!(case_detail_id: @case_detail.id)
      end
    end
  end
end

app/controllers/documenters/case_details/individual_victims_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class IndividualVictimsController < Documenters::BaseController
      layout "documenter"

      def index
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victims = @case_detail.individual_victims
      end

      def show
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victim = @case_detail.individual_victims.find(params.fetch(:id))
      end

      def new
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victim = ::CaseDetails::Victims::Individual.new
      end

      def edit
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victim = Victims::IndividualVictim.find(params.fetch(:id))
      end

      def create
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victim = ::CaseDetails::Victims::Individual.new(individual_victim_params)
        if @individual_victim.valid?
          @individual_victim.execute
          redirect_to(documenters_case_detail_individual_victims_url(@case_detail))
        else
          render(:new, status: :unprocessable_entity)
        end
      end

      def update
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victim = Victims::IndividualVictim.find(params.fetch(:id))
        if @individual_victim.update(update_params)
          redirect_to(documenters_case_detail_individual_victim_url(id: @individual_victim.id, case_detail_id: @case_detail.id))
        else
          render(:edit, status: :unprocessable_entity)
        end
      end

      private

      def individual_victim_params
        params.require(:case_details_victims_individual)
          .permit(:gender,
            :full_name,
            :dependent_type,
            :ethnic_identity,
            :victim_role,
            :dependent_details,
            :age_bracket_id,
            :date_of_birth_day,
            :date_of_birth_month,
            :date_of_birth_year)
          .merge!(case_detail: @case_detail)
      end

      def update_params
        params.require(:victims_individual_victim)
          .permit(:gender,
            :full_name,
            :dependent_type,
            :ethnic_identity,
            :victim_role,
            :dependent_details,
            :age_bracket_id,
            :date_of_birth_day,
            :date_of_birth_month,
            :date_of_birth_year)
      end
    end
  end
end

app/controllers/documenters/dashboard_controller.rb
# frozen_string_literal: true

module Documenters
  class DashboardController < BaseController
    def index
      @dashboard = "#{current_user.role.titleize.delete(" ")}Dashboard".constantize.run!
      respond_to do |format|
        format.html
        format.xlsx
      end
    end
  end
end

app/views/documenters/dashboard/index.html.erb
<div class="px-4 sm:px-6 md:px-12 lg:px-20">
  <div class="md:col-span-6 mt-6 ml-0 sm:ml-2">
    <!-- Header and Download Button -->
    <div class="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3">
      <h1 class="text-xl font-semibold text-gray-900 mb-0">Key Data Points</h1>
      <%= link_to 'Download', documenters_dashboard_index_path(format: 'xlsx'), class:"py-2 px-5 text-sm font-semibold text-gray-900 bg-white border border-gray-300 rounded-md hover:bg-gray-100 hover:text-blue-700 transition" %>
    </div>

    <!-- Summary Pills Grid -->
    <div class="grid grid-cols-2 sm:grid-cols-2 md:grid-cols-4 gap-5 mt-5">
      <% summary_data = [
        { path: "/documenters/case_details", label: "Total Cases", count: @dashboard[:case_details_count], sub: @dashboard[:current_year_case_details_count], color: "bg-red-100 text-red-700" },
        { path: "/criminalizations", label: "Criminalizations", count: @dashboard[:criminalizations_count], sub: @dashboard[:current_year_criminalizations_count], color: "bg-yellow-100 text-yellow-700" },
        { path: "/killings", label: "Killings", count: @dashboard[:killings_count], sub: @dashboard[:current_year_killings_count], color: "bg-blue-100 text-blue-700" },
        { path: "/human_rights_violations", label: "Other Violations", count: @dashboard[:human_rights_violations_count], sub: @dashboard[:current_year_human_rights_violations_count], color: "bg-green-100 text-green-700" }
      ] %>

      <% summary_data.each do |item| %>
        <a href="<%= item[:path] %>" class="p-5 rounded-xl border border-gray-200 hover:shadow-md transition bg-white flex flex-col justify-between">
          <div class="flex flex-col gap-1">
            <div class="text-xs font-semibold text-gray-500 uppercase tracking-wide"><%= item[:label] %></div>
            <div class="text-3xl font-extrabold text-gray-900 leading-tight"><%= item[:count] %></div>
            <div class="text-xs <%= item[:color] %> rounded-full px-3 py-1 w-fit mt-2 font-semibold">
              <%= item[:sub] %> this year
            </div>
          </div>
        </a>
      <% end %>
    </div>
  </div>

  <div class="border-t border-gray-200 mt-6 mb-6"></div>

  <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
    <!-- Leaderboard Column -->
    <div class="lg:col-span-1">
      <h2 class="text-xl font-semibold text-gray-800 mb-6">Human Rights Violations</h2>
      <ul class="space-y-3">
        <% @dashboard[:human_rights_violations].sort_by(&:sort_order).each_with_index do |item, index| %>
          <li class="flex justify-between items-center bg-white border border-gray-200 rounded-lg px-5 py-4 shadow-sm hover:bg-gray-50 transition">
            <%= link_to item.title, documenters_case_details_path(category_id: item.id, category_class: item.category_class), class: "text-gray-900 font-semibold hover:underline text-base" %>
            <span class="text-xl font-bold text-gray-800"><%= item.count %></span>
          </li>
        <% end %>
      </ul>
    </div>

   <!-- Charts Column -->
<div class="lg:col-span-2 space-y-8 ml-5">
  <h2 class="text-xl font-semibold text-gray-800">Individual Victims</h2>

  <!-- Both charts stacked vertically -->
  <div class="flex flex-col gap-8">

    <div>
      <h3 class="font-semibold text-gray-900 mb-4 flex items-center gap-4 text-lg">
        By Gender
        <% total_victims = Victims::IndividualVictim.count %>
        <span class="inline-block bg-blue-100 text-blue-800 text-xs font-semibold px-3 py-1 rounded-full whitespace-nowrap">
          Total: <%= total_victims %>
        </span>
      </h3>

      <% gender_counts = Victims::IndividualVictim.group(:gender).count %>

      <% male_count = gender_counts["male"] || 0 %>
      <% female_count = gender_counts["female"] || 0 %>
      <% lgbtqia_count = gender_counts["lgbtqia"] || 0 %>

      <% total_count = Victims::IndividualVictim.count.nonzero? || 1 %>
      <% others_count = total_count - male_count - female_count - lgbtqia_count %>
      <% others_count = 0 if others_count.negative? %>

      <% segments = [
        { label: "Male", count: male_count, color: "bg-blue-600" },
        { label: "Female", count: female_count, color: "bg-pink-600" },
        { label: "LGBTQIA", count: lgbtqia_count, color: "bg-purple-600" },
        { label: "No Information", count: others_count, color: "bg-gray-400" }
      ] %>

      <div class="w-full bg-gray-200 rounded-lg h-8 overflow-hidden flex shadow-inner">
        <% segments.each do |segment| %>
          <% next if segment[:count] == 0 %>
          <% width_percent = (segment[:count].to_f / total_count) * 100 %>
          <div
            class="<%= segment[:color] %> h-8"
            style="width: <%= width_percent %>%;"
            title="<%= "#{segment[:label]}: #{segment[:count]} (#{width_percent.round(1)}%)" %>"
          ></div>
        <% end %>
      </div>

      <div class="flex flex-wrap justify-start gap-6 mt-4 text-sm text-gray-700 font-medium">
        <% segments.each do |segment| %>
          <% next if segment[:count] == 0 %>
          <div class="flex items-center space-x-2 whitespace-nowrap">
            <div class="w-5 h-5 <%= segment[:color] %> rounded"></div>
            <span><%= segment[:label] %> (<%= segment[:count] %>)</span>
          </div>
        <% end %>
      </div>
    </div>

    <div>
      <h3 class="font-semibold text-gray-900 mb-2 text-lg">By Age Bracket</h3>
      <%= bar_chart AgeBracket.chart_data, height: '280px' %>
    </div>

  </div>
</div>

</div>
  <header class="pt-12">
    <h1 class="text-xl font-bold text-gray-900 mb-6">Cases By Country</h1>
  </header>
  <div class="border-t border-gray-200 mb-8"></div>
  <div id="geo_chart_div" class="w-full max-w-[1300px] h-[800px] mx-auto"></div>

</div>

<script src="https://www.gstatic.com/charts/loader.js"></script>
<script>
  google.charts.load('current', { packages: ['geochart'] });
  google.charts.setOnLoadCallback(drawRegionsMap);

  var countryMap = {
    <% Country.all.each_with_index do |country, idx| %>
      "<%= j country.name %>": "<%= country.id %>"<%= ',' unless idx == Country.count - 1 %>
    <% end %>
  };

  var countryShowUrlTemplate = "<%= country_path('__ID__') %>";

  function drawRegionsMap() {
    var data = google.visualization.arrayToDataTable([
      ['Country', 'Cases', { role: 'tooltip', p: {html: true} }],
      <% CaseDetails::CaseDetail
          .joins(:country)
          .group('countries.name', 'countries.id', 'countries.killings_count', 'countries.criminalizations_count', 'countries.human_rights_violations_count')
          .select('countries.name, countries.id, countries.killings_count, countries.criminalizations_count, countries.human_rights_violations_count, COUNT(case_details.id) as cases_count')
          .each do |record| %>
        [
          '<%= j record.name %>', 
          <%= record.cases_count %>, 
          `<div style="min-width: 150px; padding: 2px;">
             Cases: <%= record.cases_count %><br>
             Killings: <%= record.killings_count || 0 %><br>
             Criminalizations: <%= record.criminalizations_count || 0 %><br>
             Other Violations: <%= record.human_rights_violations_count || 0 %>
           </div>`
        ]<%= ',' unless record == CaseDetails::CaseDetail.last %>
      <% end %>
    ]);

    var options = {
      colorAxis: { colors: ["#ffd6d6", "#8A0303"] },
      backgroundColor: '#f9fafb',
      datalessRegionColor: '#eee',
      tooltip: { isHtml: true },
      legend: 'none'
    };

    var chart = new google.visualization.GeoChart(document.getElementById('geo_chart_div'));

    google.visualization.events.addListener(chart, 'select', function () {
      var selection = chart.getSelection();
      if (selection.length) {
        var selectedItem = selection[0];
        var countryName = data.getValue(selectedItem.row, 0);
        var countryId = countryMap[countryName];
        if (countryId) {
          window.location.href = countryShowUrlTemplate.replace('__ID__', countryId);
        }
      }
    });

    chart.draw(data, options);
  }

  window.addEventListener('resize', drawRegionsMap);
</script>