config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :test_helpers do
    post "sign_in", to: "sessions#create"
  end

  namespace :admin do
    resources :case_details do
      resources :rights_violations, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :collective_victims
      resources :individual_victims
      resources :criminalizations
      resources :killings
    end
    resources :rights_violations, shallow: true do
      resources :perpetratorizations
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue
    ActiveAdmin::DatabaseHitDuringLoad
  end

  root "documenters/sessions#new"

  resources :development_projects, only: [:show, :edit, :update]
  resources :case_details, except: [:destroy] do
    resources :victims, only: [:index], controller: "case_details/victims"
    resources :individual_victims, only: [:new, :create], controller: "case_details/individual_victims"
    resources :collective_victims, only: [:new, :create], controller: "case_details/collective_victims"
    resources :criminalizations, only: [:index, :new, :create, :edit, :update], controller: "case_details/criminalizations"
    resources :human_rights_violations, only: [:index, :new, :create, :edit, :update], controller: "case_details/human_rights_violations"
    resources :killings, only: [:index, :new, :create, :edit, :update], controller: "case_details/killings"
    resources :development_projects, only: [:index, :new, :create], controller: "case_details/development_projects"
    resources :tags, only: [:index, :create], controller: "case_details/tags"
  end

  namespace :ip_rights do
    resources :case_details, only: [:show] do
      resources :data_sharings,           only: [:new, :create]
      resources :incident_details,        only: [:new, :create]
      resources :victims,                 only: [:index]
      resources :individual_victims,      only: [:new, :create]
      resources :collective_victims,      only: [:new, :create]
      resources :human_rights_violations, only: [:index, :new, :create]
      resources :criminalizations,        only: [:new, :create]
      resources :killings,                only: [:new, :create]
      resources :impact_and_actions,      only: [:new, :create]
      resources :development_projects,    only: [:index, :new, :create]
      resources :submissions, only: [:create]
    end

    resources :documenter_details, only: [:new, :create]
  end

  resources :case_imports, only: [:show]

  resources :draft_case_details, only: [:show, :update] do
    resource :publication, only: [:create], controller: "draft_case_details/publications"
  end

  namespace :documenters do
    resources :case_imports, only: [:new, :create]
    resources :documenter, only: [] do
      resource :locale
    end
    get "/login", to: "sessions#new"
    post "/sessions", to: "sessions#create"
    delete "/sessions", to: "sessions#destroy"
    resources :dashboard, only: [:index]
    resources :individual_victims, only: [:index, :show] do
      resources :case_details, only: [:index], controller: "/documenters/individual_victims/case_details"
    end
    resources :collective_victims, only: [:index, :show, :edit, :update]
    resources :case_details, only: [:index, :new, :show] do
      resources :individual_victims, only: [:new, :create, :show, :edit, :update, :index], controller: "case_details/individual_victims"
      resources :collective_victims, only: [:new, :create, :edit, :update, :show, :index], controller: "case_details/collective_victims"
      resources :criminalizations, only: [:index, :new, :create, :edit, :update, :show], controller: "case_details/criminalizations"
      resources :human_rights_violations, only: [:index, :new, :create, :edit, :update], controller: "case_details/human_rights_violations"
      resources :killings, only: [:index, :new, :create, :edit, :update], controller: "case_details/killings"
      resources :development_projects, only: [:index, :new, :create, :show, :edit, :update], controller: "case_details/development_projects"
      resources :tags, only: [:create, :destroy], controller: "case_details/tags"
    end
  end

  resources :countries, only: [:index, :show] do
    resources :killings, only: [:index], controller: "countries/killings"
    resources :criminalizations, only: [:index], controller: "countries/criminalizations"
    resources :human_rights_violations, only: [:index], controller: "countries/human_rights_violations"
  end

  resources :killings, only: [:index, :show, :edit, :update]
  resources :criminalizations, only: [:index]
  resources :human_rights_violations, only: [:index]

  resources :case_details, only: [:edit, :update] do
    resources :development_projects, only: [:new, :create], controller: "case_details/development_projects"
  end
end

app/models/criminalizations/criminalization.rb
# frozen_string_literal: true

module Criminalizations
  class Criminalization < ApplicationRecord
    belongs_to :case_detail, class_name: "CaseDetails::CaseDetail"
    has_many :accuserizations, class_name: "Criminalizations::Accuserization", dependent: :destroy
    has_many :accuser_categories, class_name: "Criminalizations::AccuserCategory", through: :accuserizations

    counter_culture [:case_detail, :country]


    BOOLEAN_STATUSES = {
      "yes" => "Yes",
      "no" => "No",
      "no_information" => "No Information"
    }

    def self.submitted_current_year
      joins(:case_detail).where("case_details.submission_date_year" => Date.current.year)
    end

    def self.ransackable_attributes(auth_object = nil)
      ["accusation_or_charges_details", "accuser_details", "case_decision_details", "case_decision_status", "case_detail_id", "case_filing_against_perpetrator", "case_filing_against_perpetrator_details", "case_filing_details", "case_filing_status", "created_at", "criminalization_details", "experienced_harrassment_or_intimidation", "harrassment_or_intimidation_details", "id", "id_value", "impact_to_community_details", "impact_to_victim_details", "investigation_on_criminalization", "investigation_on_criminalization_details", "policies_or_laws_used", "state_action_to_address_criminalization", "state_action_to_address_criminalization_details", "updated_at", "victims_in_detention", "victims_in_detention_details"]
    end
  end
end

app/controllers/case_details_controller.rb
# frozen_string_literal: true

class CaseDetailsController < Documenters::BaseController
  layout "documenter"
  def index
    outcome = ::CaseDetails::Index.run(params.merge!(documenter: current_documenter))
    @country = Country.find_by(id: params[:country_id])
    @pagy, @case_details = pagy(outcome.result)

    respond_to do |format|
      format.html
      format.turbo_stream 
    end
  end

  def show
    @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:id))
    respond_to do |format|
      format.html
      format.turbo_stream do 
        render partial: "documenters/case_details/partials/show", 
        locals: { case_detail: @case_detail } 
      end
      format.pdf do
        pdf = CaseDetailPdf.new(@case_detail, view_context)
        send_data pdf.render, filename: "case_detail_#{@case_detail.id}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end
  
  def edit
    @case_detail = CaseDetails::CaseDetail.find(params[:id])
  end

  def update
    @case_detail = CaseDetails::CaseDetail.find(params[:id])
    @case_detail.update(case_detail_params)
    if @case_detail.valid?
      @case_detail.save
      respond_to do |format|
        format.html { redirect_to documenters_case_detail_url(@case_detail) }
      end
    else
      respond_to do |_format|
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private

  def case_detail_params
    params.require(:case_details_case_detail)
      .permit(
        :documenter_first_name,
        :documenter_last_name,
        :organization_name,
        :submission_date_year,
        :submission_date_month,
        :submission_date_day,
        :documenter_email,
        :documenter_phone_number,
        :data_sources,
        :data_sharing,
        :primary_data,
        :country_id,
        :subnational_location,
        :location_details_1,
        :location_details_2,
        :incident_start_month,
        :incident_start_day,
        :incident_start_year,
        :incident_end_month,
        :incident_end_day,
        :incident_end_year,
        :incident_hour,
        :incident_minute,
        :actions_taken_details,
        :incident_investigation_details
      )
  end
end

app/controllers/countries/criminalizations_controller.rb
# frozen_string_literal: true

module Countries
  class CriminalizationsController < ApplicationController
    layout "documenter"
    def index
      @country = Country.find(params[:country_id])
      @pagy, @criminalizations = pagy(@country.criminalizations.includes(:case_detail).order(:created_at))
    end
  end
end

app/controllers/criminalizations_controller.rb
# frozen_string_literal: true

class CriminalizationsController < ApplicationController
  layout "documenter"

  def index
    @pagy, @criminalizations = pagy(Criminalizations::Criminalization.order(created_at: :desc))
  end
end

app/controllers/documenters/case_details/collective_victims_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class CollectiveVictimsController < Documenters::BaseController
      layout "documenter"

      before_action :set_case_detail
      before_action :set_collective_victim, only: [:show, :edit, :update]

      def index
        @collective_victims = @case_detail.collective_victims
      end

      def show; end

      def new
        @collective_victim = ::CaseDetails::Victims::Collective.new
      end

      def edit
        build_missing_age_bracket_breakdowns
      end

      def create
        @collective_victim = ::CaseDetails::Victims::Collective.new(collective_victim_params)

        if @collective_victim.valid?
          @collective_victim.process!
          redirect_to(documenters_case_detail_collective_victims_url(@case_detail))
        else
          render(:new, status: :unprocessable_entity)
        end
      end

      def update
        if @collective_victim.update(update_params)
          redirect_to(documenters_case_detail_collective_victim_url(@case_detail, @collective_victim))
        else
          build_missing_age_bracket_breakdowns if @collective_victim.age_bracket_breakdowns.empty?
          render(:edit, status: :unprocessable_entity)
        end
      end

      private

      def set_case_detail
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
      end

      def set_collective_victim
        @collective_victim = Victims::CollectiveVictim.find(params[:id])
      end

      def collective_victim_params
        base_params(:case_details_victims_collective)
          .merge(case_detail_id: @case_detail.id)
      end

      def update_params
        base_params(:victims_collective_victim)
      end

      def base_params(key)
        params.require(key).permit(
          :affected_total,
          :collective_victim_category_id,
          :indigenous_group_description,
          :refer_to_individuals,
          :victim_details,
          :male_total,
          :female_total,
          age_bracket_breakdowns_attributes: [:id, :age_bracket_id, :total, :_destroy],
        )
      end

      def build_missing_age_bracket_breakdowns
        existing_ids = @collective_victim.age_bracket_breakdowns.map(&:age_bracket_id)
        AgeBracket.where.not(id: existing_ids).each do |ab|
          @collective_victim.age_bracket_breakdowns.build(age_bracket_id: ab.id)
        end
      end
    end
  end
end

app/controllers/documenters/case_details/criminalizations_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class CriminalizationsController < Documenters::BaseController
      layout "documenter"
      
      before_action :set_case_detail

      def index
        @criminalizations = @case_detail.criminalizations
      end

      def new
        @criminalization = @case_detail.criminalizations.build
        @criminalization.accuserizations.build
       
      end

      def create
        @criminalization = @case_detail.criminalizations.create!(criminalization_params)
        if @criminalization.valid?
          @criminalization.save

          respond_to do |format|
            format.html do
              redirect_to documenters_case_detail_criminalization_url(case_detail_id: @case_detail.id, id: @criminalization.id)
            end
          end
        else
          respond_to do |format|
            format.html do
              render :new, status: :unprocessable_entity
            end
          end
        end
      end

      def show
        @criminalization = @case_detail.criminalizations.find(params[:id])
      end

      def edit
        @criminalization = @case_detail.criminalizations.find(params[:id])
        Criminalizations::AccuserCategory.all.each do |category|
    unless @criminalization.accuserizations.exists?(accuser_category_id: category.id)
      @criminalization.accuserizations.build(accuser_category_id: category.id)
    end
  end
      end

      def update
        @criminalization = @case_detail.criminalizations.find(params[:id])
        
        if @criminalization.update!(criminalization_params)
          
              redirect_to documenters_case_detail_criminalization_url(case_detail_id: @case_detail.id, id: @criminalization.id)
            
        else
         
              render :edit, status: :unprocessable_entity
           

        end
      end

      private
      def set_case_detail
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
      end

      def criminalization_params
        params.require(:criminalizations_criminalization)
          .permit(
            :criminalization_details,
            :experienced_harrassment_or_intimidation,
            :harrassment_or_intimidation_details,
            :accusation_or_charges_details,
            :policies_or_laws_used,
            :accuser_details,
            :case_filing_status,
            :case_filing_details,
            :case_decision_status,
            :case_decision_details,
            :victims_in_detention,
            :victims_in_detention_details,
            :case_filing_against_perpetrator,
            :case_filing_against_perpetrator_details,
            :state_action_to_address_criminalization,
            :state_action_to_address_criminalization_details,
            :investigation_on_criminalization,
            :investigation_on_criminalization_details,
            :impact_to_victim_details,
            :impact_to_community_details,
            accuser_category_ids: []
          )
      end
    end
  end
end

app/controllers/documenters/case_details/individual_victims_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class IndividualVictimsController < Documenters::BaseController
      layout "documenter"

      def index
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victims = @case_detail.individual_victims
      end

      def show
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victim = @case_detail.individual_victims.find(params.fetch(:id))
      end

      def new
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victim = ::CaseDetails::Victims::Individual.new
      end

      def edit
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victim = Victims::IndividualVictim.find(params.fetch(:id))
      end

      def create
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victim = ::CaseDetails::Victims::Individual.new(individual_victim_params)
        if @individual_victim.valid?
          @individual_victim.execute
          redirect_to(documenters_case_detail_individual_victims_url(@case_detail))
        else
          render(:new, status: :unprocessable_entity)
        end
      end

      def update
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @individual_victim = Victims::IndividualVictim.find(params.fetch(:id))
        if @individual_victim.update(update_params)
          redirect_to(documenters_case_detail_individual_victim_url(id: @individual_victim.id, case_detail_id: @case_detail.id))
        else
          render(:edit, status: :unprocessable_entity)
        end
      end

      private

      def individual_victim_params
        params.require(:case_details_victims_individual)
          .permit(:gender,
            :full_name,
            :dependent_type,
            :ethnic_identity,
            :victim_role,
            :dependent_details,
            :age_bracket_id,
            :date_of_birth_day,
            :date_of_birth_month,
            :date_of_birth_year)
          .merge!(case_detail: @case_detail)
      end

      def update_params
        params.require(:victims_individual_victim)
          .permit(:gender,
            :full_name,
            :dependent_type,
            :ethnic_identity,
            :victim_role,
            :dependent_details,
            :age_bracket_id,
            :date_of_birth_day,
            :date_of_birth_month,
            :date_of_birth_year)
      end
    end
  end
end

app/views/documenters/case_details/criminalizations/_show_row.html.erb
<!-- app/views/criminalizations/_show_row.html.erb -->
<div class="border-t border-gray-200 pt-6">
  <h2 class="text-sm font-semibold text-gray-800 mb-2"><%= label %></h2>
    <p class="text-gray-700 whitespace-pre-line"><%= value.presence || '—' %></p>
</div>

app/views/documenters/case_details/criminalizations/edit.html.erb
<%= simple_form_for @criminalization, url: documenters_case_detail_criminalization_path, method: :patch do |f| %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>

app/views/documenters/case_details/criminalizations/new.html.erb
<%= simple_form_for @criminalization, url: documenters_case_detail_criminalizations_path do |f| %>
  <%= render partial: "form", locals: { f: f } %>
<% end %>

app/views/documenters/case_details/criminalizations/show.html.erb
<div class="max-w-7xl mx-auto px-10 mt-5 mb-5 py-10 bg-white shadow border-t-4 space-y-10">
  <div class="flex flex-col md:flex-row md:items-center md:justify-between space-y-4 md:space-y-0">
    <!-- Left: Title -->
    <div class="flex items-center space-x-4">
      <h1 class="text-xl font-bold text-gray-900">Criminalization Details</h1>

      <% if @criminalization.victims_in_detention.to_s.downcase.in?(%w[yes true 1]) %>
        <span class="inline-block bg-red-600 text-white text-xs font-semibold px-3 py-1 rounded-full">
          In Detention
        </span>
      <% end %>
    </div>

    <!-- Right: Action Buttons -->
    <div class="flex space-x-3 justify-start md:justify-end">
      <%= link_to "Back", documenters_case_detail_criminalizations_path(@case_detail),
                  class: "inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-lg" %>
      <%= link_to "Edit", edit_documenters_case_detail_criminalization_path(case_detail_id: @case_detail.id, id: @criminalization.id),
                  class: "inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-stone-600 hover:bg-stone-700 rounded-lg" %>
    </div>
  </div>

    <%= render 'show_row', label: "Why was/were the victim/s criminalized?", value: @criminalization.criminalization_details %>

    <%= render 'show_row', label: "Did the victim/s experience any form of harassment or intimidation prior to criminalization?", value: humanize_yes_no(@criminalization.experienced_harrassment_or_intimidation) %>
    <% if @criminalization.experienced_harrassment_or_intimidation == 'yes' %>
      <%= render 'show_row', label: "If YES, please provide more information", value: @criminalization.harrassment_or_intimidation_details %>
    <% end %>

    <%= render 'show_row', label: "What was/were the accusation/s or charge/s filed against the victim/s?", value: @criminalization.accusation_or_charges_details %>
    <%= render 'show_row', label: "What was/were the policy/ies or law/s or institutional justification/s used against the victim/s?", value: @criminalization.policies_or_laws_used %>

    <% accusers = @criminalization.accuserizations.includes(:accuser_category).map { |a| a.accuser_category.title }.join(', ') %>
    <%= render 'show_row', label: "Who put forward the accusation/s or charge/s against the victim/s?", value: accusers.presence || 'None' %>
    <%= render 'show_row', label: "Please provide more information about the accuser/s", value: @criminalization.accuser_details %>

    <%= render 'show_row', label: "Was/were the accusation/s or charge/s against the victim legally or formally filed?", value: humanize_yes_no(@criminalization.case_filing_status) %>
    <%= render 'show_row', label: "If YES, where was the case/s filed? (e.g., regional court, military court, supreme court, etc.)", value: @criminalization.case_filing_details %>
    <%= render 'show_row', label: "If NO, Please provide more information", value: @criminalization.case_filing_details %>

    <%= render 'show_row', label: "Is there a decision on the legal or formal accusation/s or charge/s filed against the victim/s?", value: humanize_yes_no(@criminalization.case_decision_status) %>
    <%= render 'show_row', label: "Please provide more information", value: @criminalization.case_decision_details %>

    <%= render 'show_row', label: "Is/Are the victim/s in prison or detention facility?", value: humanize_yes_no(@criminalization.victims_in_detention) %>
    <%= render 'show_row', label: "If yes, please provide more information on their conditions or situation in the prison or detention facility—do they know where is the prison or detention facility located? Are they allowed visitors?", value: @criminalization.victims_in_detention_details %>
    <%= render 'show_row', label: "If no, please provide more information on the current situation of the victim/s—Is/Are s/he/they in hiding? Released on bail? Awaiting court trial? On house arrest? etc", value: @criminalization.victims_in_detention_details %>

    <%= render 'show_row', label: "Was/Were there (a) legal case/s filed against the alleged perpetrators on behalf of the victim/s criminalized?", value: humanize_yes_no(@criminalization.case_filing_against_perpetrator) %>
    <%= render 'show_row', label: "If yes, please provide further information: Where is/are the case/s filed? Who filed the case? E.g., victim, family of the victim, support organizations, etc.; any other details of the case/s filed, please share.", value: @criminalization.case_filing_against_perpetrator_details %>
    <%= render 'show_row', label: "If no, please elaborate on your response (e.g. can you provide probable reasons on why there has been no legal case/s filed against the alleged perpetrators? Etc.)", value: @criminalization.case_filing_against_perpetrator_details %>

    <%= render 'show_row', label: "Has the State undertaken any action/s to address the incident of criminalization?", value: humanize_yes_no(@criminalization.state_action_to_address_criminalization) %>
    <%= render 'show_row', label: "If YES, please provide more information on the action/s undertaken, including any relevant results.", value: @criminalization.state_action_to_address_criminalization_details %>
    <%= render 'show_row', label: "If NO, please elaborate on your response", value: @criminalization.state_action_to_address_criminalization_details %>

    <h2 class="font-bold text-xl text-gray-900 pt-5 mt-5 border-t">Impact/s of the Incident/s of Human Rights Violation</h2>

    <%= render 'show_row', label: "How did the incident/s affect the victim/s and his/her/their family?", value: @criminalization.impact_to_victim_details %>
    <%= render 'show_row', label: "How did the incident/s affect the Indigenous Peoples group/s or community/ies and/or organization of the victim/s?", value: @criminalization.impact_to_community_details %>

  </div>
</div>