config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :test_helpers do
    post "sign_in", to: "sessions#create"
  end

  namespace :admin do
    resources :case_details do
      resources :rights_violations, only: [:index, :show, :new, :create, :edit, :update, :destroy]
      resources :collective_victims
      resources :individual_victims
      resources :criminalizations
      resources :killings
    end
    resources :rights_violations, shallow: true do
      resources :perpetratorizations
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  begin
    ActiveAdmin.routes(self)
  rescue
    ActiveAdmin::DatabaseHitDuringLoad
  end

  root "documenters/sessions#new"

  resources :development_projects, only: [:show, :edit, :update]
  resources :case_details, except: [:destroy] do
    resources :victims, only: [:index], controller: "case_details/victims"
    resources :individual_victims, only: [:new, :create], controller: "case_details/individual_victims"
    resources :collective_victims, only: [:new, :create], controller: "case_details/collective_victims"
    resources :criminalizations, only: [:index, :new, :create, :edit, :update], controller: "case_details/criminalizations"
    resources :human_rights_violations, only: [:index, :new, :create, :edit, :update], controller: "case_details/human_rights_violations"
    resources :killings, only: [:index, :new, :create, :edit, :update], controller: "case_details/killings"
    resources :development_projects, only: [:index, :new, :create], controller: "case_details/development_projects"
    resources :tags, only: [:index, :create], controller: "case_details/tags"
  end

  namespace :ip_rights do
    resources :case_details, only: [:show] do
      resources :data_sharings,           only: [:new, :create]
      resources :incident_details,        only: [:new, :create]
      resources :victims,                 only: [:index]
      resources :individual_victims,      only: [:new, :create]
      resources :collective_victims,      only: [:new, :create]
      resources :human_rights_violations, only: [:index, :new, :create]
      resources :criminalizations,        only: [:new, :create]
      resources :killings,                only: [:new, :create]
      resources :impact_and_actions,      only: [:new, :create]
      resources :development_projects,    only: [:index, :new, :create]
      resources :submissions, only: [:create]
    end

    resources :documenter_details, only: [:new, :create]
  end

  resources :case_imports, only: [:show]

  resources :draft_case_details, only: [:show, :update] do
    resource :publication, only: [:create], controller: "draft_case_details/publications"
  end

  namespace :documenters do
    resources :case_imports, only: [:new, :create]
    resources :documenter, only: [] do
      resource :locale
    end
    get "/login", to: "sessions#new"
    post "/sessions", to: "sessions#create"
    delete "/sessions", to: "sessions#destroy"
    resources :dashboard, only: [:index]
    resources :individual_victims, only: [:index, :show] do
      resources :case_details, only: [:index], controller: "/documenters/individual_victims/case_details"
    end
    resources :collective_victims, only: [:index, :show, :edit, :update]
    resources :case_details, only: [:index, :new, :show] do
      resources :individual_victims, only: [:new, :create, :show, :edit, :update, :index], controller: "case_details/individual_victims"
      resources :collective_victims, only: [:new, :create, :edit, :update, :show, :index], controller: "case_details/collective_victims"
      resources :criminalizations, only: [:index, :new, :create, :edit, :update, :show], controller: "case_details/criminalizations"
      resources :human_rights_violations, only: [:index, :new, :create, :edit, :update], controller: "case_details/human_rights_violations"
      resources :killings, only: [:index, :new, :create, :edit, :update], controller: "case_details/killings"
      resources :development_projects, only: [:index, :new, :create, :show, :edit, :update], controller: "case_details/development_projects"
      resources :tags, only: [:create, :destroy], controller: "case_details/tags"
    end
  end

  resources :countries, only: [:index, :show] do
    resources :killings, only: [:index], controller: "countries/killings"
    resources :criminalizations, only: [:index], controller: "countries/criminalizations"
    resources :human_rights_violations, only: [:index], controller: "countries/human_rights_violations"
  end

  resources :killings, only: [:index, :show, :edit, :update]
  resources :criminalizations, only: [:index]
  resources :human_rights_violations, only: [:index]

  resources :case_details, only: [:edit, :update] do
    resources :development_projects, only: [:new, :create], controller: "case_details/development_projects"
  end
end

app/controllers/case_details_controller.rb
# frozen_string_literal: true

class CaseDetailsController < Documenters::BaseController
  layout "documenter"
  def index
    outcome = ::CaseDetails::Index.run(params.merge!(documenter: current_documenter))
    @country = Country.find_by(id: params[:country_id])
    @pagy, @case_details = pagy(outcome.result)

    respond_to do |format|
      format.html
      format.turbo_stream 
    end
  end

  def show
    @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:id))
    respond_to do |format|
      format.html
      format.turbo_stream do 
        render partial: "documenters/case_details/partials/show", 
        locals: { case_detail: @case_detail } 
      end
      format.pdf do
        pdf = CaseDetailPdf.new(@case_detail, view_context)
        send_data pdf.render, filename: "case_detail_#{@case_detail.id}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end
  
  def edit
    @case_detail = CaseDetails::CaseDetail.find(params[:id])
  end

  def update
    @case_detail = CaseDetails::CaseDetail.find(params[:id])
    @case_detail.update(case_detail_params)
    if @case_detail.valid?
      @case_detail.save
      respond_to do |format|
        format.html { redirect_to documenters_case_detail_url(@case_detail) }
      end
    else
      respond_to do |_format|
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private

  def case_detail_params
    params.require(:case_details_case_detail)
      .permit(
        :documenter_first_name,
        :documenter_last_name,
        :organization_name,
        :submission_date_year,
        :submission_date_month,
        :submission_date_day,
        :documenter_email,
        :documenter_phone_number,
        :data_sources,
        :data_sharing,
        :primary_data,
        :country_id,
        :subnational_location,
        :location_details_1,
        :location_details_2,
        :incident_start_month,
        :incident_start_day,
        :incident_start_year,
        :incident_end_month,
        :incident_end_day,
        :incident_end_year,
        :incident_hour,
        :incident_minute,
        :actions_taken_details,
        :incident_investigation_details
      )
  end
end

app/controllers/documenters/base_controller.rb
# frozen_string_literal: true

module Documenters
  class BaseController < ApplicationController
    before_action :authenticate_documenter!
    helper_method :current_documenter
    layout "documenter"
    around_action :switch_locale

    def switch_locale(&action)
      locale = current_documenter ? current_documenter.locale : I18n.default_locale
      I18n.with_locale(locale, &action)
    end

    def current_documenter
      if session[:user_id]
        @documenter = Users::Documenter.find(session[:user_id])
      end
    end

    def logged_in?
      !!current_documenter
    end

    def authenticate_documenter!
      redirect_to documenters_login_path unless logged_in?
    end
  end
end

app/controllers/documenters/case_details/collective_victims_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class CollectiveVictimsController < Documenters::BaseController
      layout "documenter"

      before_action :set_case_detail
      before_action :set_collective_victim, only: [:show, :edit, :update]

      def index
        @collective_victims = @case_detail.collective_victims
      end

      def show; end

      def new
        @collective_victim = ::CaseDetails::Victims::Collective.new
      end

      def edit
        build_missing_age_bracket_breakdowns
      end

      def create
        @collective_victim = ::CaseDetails::Victims::Collective.new(collective_victim_params)

        if @collective_victim.valid?
          @collective_victim.process!
          redirect_to(documenters_case_detail_collective_victims_url(@case_detail))
        else
          render(:new, status: :unprocessable_entity)
        end
      end

      def update
        if @collective_victim.update(update_params)
          redirect_to(documenters_case_detail_collective_victim_url(@case_detail, @collective_victim))
        else
          build_missing_age_bracket_breakdowns if @collective_victim.age_bracket_breakdowns.empty?
          render(:edit, status: :unprocessable_entity)
        end
      end

      private

      def set_case_detail
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
      end

      def set_collective_victim
        @collective_victim = Victims::CollectiveVictim.find(params[:id])
      end

      def collective_victim_params
        base_params(:case_details_victims_collective)
          .merge(case_detail_id: @case_detail.id)
      end

      def update_params
        base_params(:victims_collective_victim)
      end

      def base_params(key)
        params.require(key).permit(
          :affected_total,
          :collective_victim_category_id,
          :indigenous_group_description,
          :refer_to_individuals,
          :victim_details,
          :male_total,
          :female_total,
          age_bracket_breakdowns_attributes: [:id, :age_bracket_id, :total, :_destroy],
        )
      end

      def build_missing_age_bracket_breakdowns
        existing_ids = @collective_victim.age_bracket_breakdowns.map(&:age_bracket_id)
        AgeBracket.where.not(id: existing_ids).each do |ab|
          @collective_victim.age_bracket_breakdowns.build(age_bracket_id: ab.id)
        end
      end
    end
  end
end

app/controllers/documenters/case_details/criminalizations_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class CriminalizationsController < Documenters::BaseController
      layout "documenter"
      
      before_action :set_case_detail

      def index
        @criminalizations = @case_detail.criminalizations
      end

      def new
        @criminalization = @case_detail.criminalizations.build
        @criminalization.accuserizations.build
       
      end

      def create
        @criminalization = @case_detail.criminalizations.create!(criminalization_params)
        if @criminalization.valid?
          @criminalization.save

          respond_to do |format|
            format.html do
              redirect_to documenters_case_detail_criminalization_url(case_detail_id: @case_detail.id, id: @criminalization.id)
            end
          end
        else
          respond_to do |format|
            format.html do
              render :new, status: :unprocessable_entity
            end
          end
        end
      end

      def show
        @criminalization = @case_detail.criminalizations.find(params[:id])
      end

      def edit
        @criminalization = @case_detail.criminalizations.find(params[:id])
        Criminalizations::AccuserCategory.all.each do |category|
    unless @criminalization.accuserizations.exists?(accuser_category_id: category.id)
      @criminalization.accuserizations.build(accuser_category_id: category.id)
    end
  end
      end

      def update
        @criminalization = @case_detail.criminalizations.find(params[:id])
        
        if @criminalization.update!(criminalization_params)
          
              redirect_to documenters_case_detail_criminalization_url(case_detail_id: @case_detail.id, id: @criminalization.id)
            
        else
         
              render :edit, status: :unprocessable_entity
           

        end
      end

      private
      def set_case_detail
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
      end

      def criminalization_params
        params.require(:criminalizations_criminalization)
          .permit(
            :criminalization_details,
            :experienced_harrassment_or_intimidation,
            :harrassment_or_intimidation_details,
            :accusation_or_charges_details,
            :policies_or_laws_used,
            :accuser_details,
            :case_filing_status,
            :case_filing_details,
            :case_decision_status,
            :case_decision_details,
            :victims_in_detention,
            :victims_in_detention_details,
            :case_filing_against_perpetrator,
            :case_filing_against_perpetrator_details,
            :state_action_to_address_criminalization,
            :state_action_to_address_criminalization_details,
            :investigation_on_criminalization,
            :investigation_on_criminalization_details,
            :impact_to_victim_details,
            :impact_to_community_details,
            accuser_category_ids: []
          )
      end
    end
  end
end

app/controllers/documenters/case_details/development_projects_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class DevelopmentProjectsController < Documenters::BaseController
      layout "documenter"

      def index
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
        @development_projects = @case_detail.development_projects
      end

      def show
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = @case_detail.development_projects.find(params[:id])
      end

      def new
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = ::CaseDetails::DevelopmentProject.new
      end

      def edit
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = DevelopmentProjects::DevelopmentProject.find(params[:id])
      end

      def create
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = ::CaseDetails::DevelopmentProject.new(development_project_params)
        if @development_project.valid?
          @development_project.save!
          redirect_to(documenters_case_detail_development_projects_url(@case_detail))
        else
          render(:new, status: :unprocessable_entity)
        end
      end

      def update
        @case_detail = ::CaseDetails::CaseDetail.find(params.fetch(:case_detail_id))
        @development_project = @case_detail.development_projects.find(params[:id])
        @development_project.update(edit_development_project_params)
        if @development_project.valid?
          @development_project.save
          redirect_to(documenters_case_detail_development_project_url(id: @development_project.id, case_detail_id: @case_detail.id))
        else
          render(:edit, status: :unprocessable_entity)
        end
      end

      private

      def edit_development_project_params
        params.require(:development_projects_development_project).permit(
          :development_project_category_id,
          :name,
          :description,
          :project_start_year,
          :website_sources,
          :parent_company_name,
          :parent_company_description,
          :parent_company_data_sources,
          :parent_company_country_id,
          :funding_source_description,
          :funding_source_data_sources,
        )
      end

      def development_project_params
        params
          .require(:case_details_development_project)
          .permit(:project_name,
            :development_project_category_id,
            :project_description,
            :start_of_operation_year,
            :project_documents,
            :project_data_sources,
            :company_profile_known,
            :company_info_status,
            :parent_company_country_id,
            :parent_company_description,
            :parent_company_documents,
            :parent_company_data_sources,
            :funding_profile_known,
            :funding_description,
            :funding_source_ids,
            :funding_source_description,
            :funding_source_documents,
            :funding_source_data_sources,
            :parent_company_name,
            documents: [])
          .merge!(case_detail_id: @case_detail.id)
      end
    end
  end
end

app/controllers/documenters/case_details/tags_controller.rb
# frozen_string_literal: true

module Documenters
  module CaseDetails
    class TagsController < Documenters::BaseController
      layout "documenter"

      before_action :set_case_detail

      def create
        tag = params[:tag]
        @case_detail.tag_list.add(tag)
        @case_detail.save

        respond_to do |format|
          format.turbo_stream
        end
      end

      def destroy
        @case_detail.tag_list.remove(params[:id])
        @case_detail.save!

        respond_to do |format|
          format.turbo_stream
          format.html { redirect_to(@case_detail) }
        end
      end

      private

      def set_case_detail
        @case_detail = ::CaseDetails::CaseDetail.find(params[:case_detail_id])
      end
    end
  end
end

app/views/documenters/case_details/index.html.erb
<div class="md:col-span-6 mt-6 ml-2">
  <turbo-frame id="case_details" data-turbo-action="advance">
    <div class="flex flex-col sm:flex-row justify-between items-center mt-5 mb-5 gap-3">

      <!-- Search Form replacing the heading -->
      <%= form_tag documenters_case_details_path, method: :get, class: "flex-grow max-w-md relative", data: { turbo_frame: "case_details" } do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search cases", type: "search",
          class: "block w-full p-2.5 pl-10 pr-10 text-sm text-gray-900 rounded-lg border border-gray-300 focus:ring-green-700 focus:border-green-500" %>

        <button type="submit"
          class="absolute right-2 top-1/2 -translate-y-1/2 bg-gray-100 hover:bg-gray-200 focus:ring-2 focus:ring-gray-300 font-medium rounded-lg p-2 h-8 w-8 flex items-center justify-center">
          <svg aria-hidden="true" class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
          </svg>
        </button>
      <% end %>

      <!-- Buttons -->
      <div class="flex gap-2 items-center">
        <%= link_to "New Case", new_ip_rights_documenter_detail_path, data: { turbo: false },
          class: "text-white bg-green-700 hover:bg-green-800 focus:ring-2 focus:ring-green-800 font-medium rounded-lg text-sm px-3 py-1.5" %>

        <%= link_to 'Upload', new_documenters_case_import_path, data: { turbo: false },
          class: "py-1.5 px-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-300 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-gray-200" %>
      </div>
    </div>

    <div class="my-4">

      <%= form_tag(documenters_case_details_path, method: :get, data: { controller: "case-details-filter", 'case-details-filter-target': "filterForm", turbo_frame: "case_details" }) do %>
        <div class="flex flex-wrap gap-4 items-center">
          <%= select_tag :country_id,
            options_for_select(Country.order(name: :asc).map { |c| [c.name, c.id] }, params[:country_id]),
            prompt: "--select country--",
            class: "bg-gray-50 text-gray-900 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-64 p-2.5 text-sm",
            data: { action: "change->case-details-filter#submit" } %>

          <%= select_tag :incident_start_year,
            options_for_select(20.years.ago.year..Date.current.year, params[:incident_start_year]),
            prompt: "--select incident year--",
            class: "bg-gray-50 text-gray-900 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-64 p-2.5 text-sm",
            data: { action: "change->case-details-filter#submit" } %>

          <%= select_tag :submission_date_year,
            options_for_select(20.years.ago.year..Date.current.year, params[:submission_date_year]),
            prompt: "--select submission year--",
            class: "bg-gray-50 text-gray-900 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-64 p-2.5 text-sm",
            data: { action: "change->case-details-filter#submit" } %>

          <%= select_tag :tag,
            options_for_select(ActsAsTaggableOn::Tag.order(name: :asc).map{ |tag| [tag.name, tag.name] }, params[:tag]),
            prompt: "--select tag--",
            class: "bg-gray-50 text-gray-900 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-64 p-2.5 text-sm",
            data: { action: "change->case-details-filter#submit" } %>
        </div>
      <% end %>

      <div class="mt-4">

        <% cleaned_params = params.to_unsafe_h.slice(:country_id, :incident_start_year, :submission_date_year, :tag).reject { |_, v| v.blank? } %>

        <% if @country.present? %>
          <%= link_to documenters_case_details_path(cleaned_params.except(:country_id)),
            data: { turbo_frame: "case_details" },
            class: "inline-flex items-center px-3 py-1 text-sm rounded-full bg-gray-100 text-gray-800 hover:bg-gray-200" do %>
            Country: <%= @country.name %> <span class="ml-2 text-red-400 hover:text-red-600 font-bold">✕</span>
          <% end %>
        <% end %>

        <% if params[:incident_start_year].present? %>
          <%= link_to documenters_case_details_path(cleaned_params.except(:incident_start_year)),
            data: { turbo_frame: "case_details", turbo_action: "advance" },
            class: "inline-flex items-center px-3 py-1 text-sm rounded-full bg-gray-100 text-gray-800 hover:bg-gray-200" do %>
            Incident Year: <div class="font-medium ml-1"> <%= params[:incident_start_year] %></div> <span class="ml-2 text-red-400 hover:text-red-600 font-bold">✕</span>
          <% end %>
        <% end %>

        <% if params[:submission_date_year].present? %>
          <%= link_to documenters_case_details_path(cleaned_params.except(:submission_date_year)),
            data: { turbo_frame: "case_details" },
            class: "inline-flex items-center px-3 py-1 text-sm rounded-full bg-gray-100 text-gray-800 hover:bg-gray-200" do %>
            Submission Year: <div class="font-medium ml-1"> <%= params[:submission_date_year] %></div> <span class="ml-2 text-red-400 hover:text-red-600 font-bold">✕</span>
          <% end %>
        <% end %>

        <% if params[:tag].present? %>
          <%= link_to documenters_case_details_path(params.to_unsafe_h.except(:tag)),
            data: { turbo_frame: "case_details", turbo_action: "advance" },
            class: "inline-flex items-center px-3 py-1 text-sm rounded-full bg-gray-100 text-gray-800 hover:bg-gray-200" do %>
            Tagged with: <div class="font-medium ml-1"> <%= params[:tag] %></div> <span class="ml-2 text-red-400 hover:text-red-600 font-bold">✕</span>
          <% end %>
        <% end %>

        <% if params[:country_id].present? || params[:incident_start_year].present? || params[:submission_date_year].present? || params[:tag].present? %> 
          <div class="mt-2 block">
            <%= link_to "Clear Filters", documenters_case_details_path, data: { turbo_frame: "case_details", turbo_action: "advance" },
              class: "items-center px-3 py-1 text-sm rounded-full bg-gray-200 text-gray-700 hover:bg-gray-300" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-span-3">
      <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
          <div class="overflow-hidden">
            <table class="mt-2 min-w-full">
              <%= render 'case_details/tables/headers' %>
              <tbody>
                <% @case_details.each do |case_detail| %>
                 <tr 
  data-controller="clickable-row" 
  data-clickable-row-url-value="<%= documenters_case_detail_path(case_detail) %>" 
  data-action="click->clickable-row#click" 
  class="border-b hover:bg-gray-100"
>
  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
    <%= case_detail.submission_date %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
    <%= case_detail.incident_start_date %>
  </td>
  <td scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap">
    <%= case_detail.organization_name.truncate(35) %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
    <%= case_detail.country_name %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
    <%= case_detail.subnational_location %>
  </td>
  <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
    <%= case_detail.data_sharing %>
  </td>
</tr>

                <% end %>
              </tbody>
            </table>
            <div class="mt-5">
              <%== pagy_nav_custom(@pagy) if @pagy.pages > 1 %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </turbo-frame>
</div>

app/views/documenters/case_details/show.html.erb
<div class="md:col-span-6 mt-6 ml-2">
            <h2 class="font-bold text-xl text-gray-900">Case Details</h2>
<div class="text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
    <ul class="flex flex-wrap -mb-px">
      <li class="mr-2">
          <a href="/documenters/case_details/<%=@case_detail.id %>" class="<%= "inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" if current_page?(documenters_case_detail_path(@case_detail.id)) %>inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300">Data</a>
      </li>
      <li class="mr-2">
          <a href="/documenters/case_details/<%=@case_detail.id %>/victims" class="<%= "inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" if current_page?(documenters_case_detail_path(@case_detail.id)) %>inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300">Victims</a>
      </li>
      <li class="mr-2">
          <a href="/documenters/individual_victims/<%=@case_detail.id %>/case_details" class="<%= "inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" if current_page?(documenters_individual_victim_case_details_path(@case_detail.id)) %>inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300">Human Rights Violations</a>
      </li>
      <li class="mr-2">
          <a href="/documenters/individual_victims/<%=@case_detail.id %>/case_details" class="<%= "inline-block p-4 text-blue-600 rounded-t-lg border-b-2 border-blue-600 active dark:text-blue-500 dark:border-blue-500" if current_page?(documenters_individual_victim_case_details_path(@case_detail.id)) %>inline-block p-4 rounded-t-lg border-b-2 border-transparent hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300">Development Projects</a>
      </li>
    </ul>

</div>
  <% if current_page?(documenters_case_detail_path(@case_detail)) %>
      <%= render 'documenters/case_details/partials/profile', case_detail: @case_detail %>
    <% end %>